<Workspace Version="1.3.1.1736" X="-1710.12481462605" Y="1024.11828248975" zoom="0.306051248781626" ScaleFactor="1" Name="Home" Description="" RunType="Manual" RunPeriod="10000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <DSRevitNodesUI.Categories guid="9c59348f-52a4-4aa8-b4b9-f0982e5e0952" type="DSRevitNodesUI.Categories" nickname="Categories" x="5696.65358776026" y="-1520.18658248271" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="166:DuctCurves" />
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="b9f62f22-08e3-44b7-84ef-8bc685a0440e" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Parameters" x="6451.18770054702" y="-1492.57873109307" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Parameters">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <DSRevitNodesUI.ElementsOfCategory guid="265aa3c4-9cb6-4d58-a91d-b26d249f6b7f" type="DSRevitNodesUI.ElementsOfCategory" nickname="All Elements of Category" x="6207.82275262702" y="-1496.67852085955" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </DSRevitNodesUI.ElementsOfCategory>
    <PythonNodeModels.PythonNode guid="7e50d76b-d3f2-435c-9da9-10548b09c3fc" type="PythonNodeModels.PythonNode" nickname="Python: String from Object" x="5953.36709485595" y="-1619.46307932203" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
category = IN[0]


#Assign your output to the OUT variable.
OUT = '"' + str(category) + '"'</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="0fad4b1f-1caf-4a6b-9f7c-0f16a734bad1" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Id" x="6216.71536502778" y="-2163.64985441428" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Id">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="8bbcacae-e796-47e4-a8c2-f0cbed06c0fa" type="PythonNodeModels.PythonNode" nickname="Python Script" x="6424.88172495371" y="-2165.75125017222" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
listIn = IN[0]

for index, i in enumerate(listIn):
	listIn[index] = "Element Id : " + str(i)

#Assign your output to the OUT variable.
OUT = listIn</Script>
    </PythonNodeModels.PythonNode>
    <PythonNodeModels.PythonNode guid="648f4ee1-e579-4549-b499-d6d4d87bbb23" type="PythonNodeModels.PythonNode" nickname="Python Script" x="6692.11138297647" y="-2170.90195509201" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
mainList = IN[0]
elementIds = IN[1]

for ele_a, ele_b in zip(mainList, elementIds):
    ele_a.insert(0, ele_b)

#Assign your output to the OUT variable.
OUT = mainList</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Watch guid="c1ad97c8-2296-4783-8cee-521c3cf28e42" type="CoreNodeModels.Watch" nickname="Watch" x="6825.77935542985" y="-2029.6404773293" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <PythonNodeModels.PythonNode guid="66055e37-dad2-4e2f-b64e-ebff6f04a1d9" type="PythonNodeModels.PythonNode" nickname="Python: Create Sublists" x="7190.09689786937" y="-2216.53793383747" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
#The inputs to this node will be stored as a list in the IN variables.
tableName = IN[0]
listOfFields = IN[1]
listOfValues = IN[2]

# Create dictionary items with first value as key
dictionary = {e[0].split(" : ")[1] : e[1:] for e in listOfValues}

#Assign your output to the OUT variable.
OUT = dictionary.items()</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Watch guid="422cd9d4-6381-4a08-9c76-d502a7edc69f" type="CoreNodeModels.Watch" nickname="Watch" x="7368.21842755928" y="-2215.25169044995" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="af567617-315f-4b53-9a60-a885277cf9bd" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="5884.47471071324" y="-2472.51088071699" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="tableName;" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="ee128686-19e6-441d-b638-9be057452344" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Command.SQLite_Command" x="8830.73717482037" y="-2578.92465519145" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="true" assembly="..\..\..\..\..\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Slingshot! for Dynamo\bin\Slingshot.dll" function="Database.Command.SQLite_Command@string,bool,string[]">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <CoreNodeModels.Input.Filename guid="242199ae-0818-4234-9394-7a5ee23996d9" type="CoreNodeModels.Input.Filename" nickname="File Path" x="8663.06433052636" y="-2684.20228105354" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.String>..\DB\Mechanical.db</System.String>
      <HintPath>C:\Users\J. Merlan\Dev Lab\RvtSql\Sandbox\Revit Data to SQLite\DB\Mechanical.db</HintPath>
    </CoreNodeModels.Input.Filename>
    <CoreNodeModels.Input.BoolSelector guid="af4978d8-1304-4dd3-a278-765ce11e1ee2" type="CoreNodeModels.Input.BoolSelector" nickname="Boolean" x="8641.0946949745" y="-2586.43740284774" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Boolean>True</System.Boolean>
    </CoreNodeModels.Input.BoolSelector>
    <PythonNodeModels.PythonNode guid="d609f85f-49d5-49d7-867a-ff1478aa59e0" type="PythonNodeModels.PythonNode" nickname="Python: Create dictionary" x="7698.01240097086" y="-2221.03986978108" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
listIn = IN[0]

oneElement = listIn[0]
oneElementId = oneElement[0]
oneElementsParams = oneElement[1]

allElements = []


for index, i in enumerate(listIn):
	allElements.append(["Element Id : " + listIn[index][0]])
	
for index, i in enumerate(listIn):
	for pIndex, p in enumerate(listIn[index][1]):
		allElements[index].append(listIn[index][1][pIndex])
		
allValues = [[] for i in listIn]
		
for index, i in enumerate(allElements):
	for pIndex, i in enumerate(allElements[index]):
		#allValues[index].append(str(allElements[index][pIndex]).split(" : ", 1)[1])
		allValues[index].append(str(allElements[index][pIndex]).split(" : "))

#myDict = dict(str(item).split(" : ") for index, item in enumerate(allElements[index]))

#for index, i in enumerate(allElements):
#	myDict.append(dict(str(item).split(" : ") for item in allElements[index]))

#Create dictionary of parameters with key from param name
#myDic = dict(str(item).split(" : ") for item in oneElementsParams)

# Add Element Id to dictionary
#myDic['Element Id'] = oneElementId

OUT = allValues

# Output dictionary with Element Id as key
#elementDict = dict(zip(listIn[0][0:][0],listIn[0][0:][1]))
#OUT = elementDict.items()

# First element
#OUT = listIn[0][0]

# Drill down to first element Id
#OUT = listIn[0][0][0]

# Drill down to first list of parameters 
#OUT = listIn[0][0][1]

# Drill down to first parameter in first list of parameters
#OUT = listIn[0][1][0]</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Watch guid="df46c5f3-6467-4ecb-9c65-c431942b3e7e" type="CoreNodeModels.Watch" nickname="Watch" x="7907.93862738967" y="-2209.02870936559" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
    <PythonNodeModels.PythonNode guid="08eb58bc-dfb2-4972-8222-1091d91e4407" type="PythonNodeModels.PythonNode" nickname="Python: SQL Command" x="8215.32415970128" y="-2514.21468001717" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
listIn = IN[0]
tableName = IN[1]

sqlCommand = "BEGIN TRANSACTION; \n"
questionMarks = ""
listOfColumns = []
columnNames = ""
columnValues = ""


for index1, i1 in enumerate(listIn):
	sqlCommand += "INSERT INTO " + tableName + " ("
	for index2, i2 in enumerate(listIn[index1]):
		sqlCommand += '"' + listIn[index1][index2][0] + '", '
	sqlCommand = sqlCommand[:-2]
	sqlCommand += ") \n VALUES ("
	for index2, i2 in enumerate(listIn[index1]):
		listIn[index1][index2][1] = listIn[index1][index2][1].replace("\"", " in")
		listIn[index1][index2][1] = listIn[index1][index2][1].replace("\'", " ft")
		listIn[index1][index2][1] = listIn[index1][index2][1].replace("ø", " Diam")
		sqlCommand += '"' + listIn[index1][index2][1] + '\", '
	sqlCommand = sqlCommand[:-2]
	sqlCommand += "); \n"
	
sqlCommand += "COMMIT;"
	
OUT = sqlCommand

	#sqlCommand += columnNames + "\n"
#	for pIndex, i in enumerate(listIn[listIndex]):
#		columnNames += listIn[listIndex][pIndex][0] + '"' + ', '
		
#for listIndex, i in enumerate(listIn):
#	for pIndex, i in enumerate(listIn[listIndex]):
#		for param, i in enumerate(listIn[listIndex][pIndex]):
#			listOfColumns.append('"' + listIn[listIndex][pIndex][0] + '"' + ', ')


#columnNames = columnNames[:-2]

#for listIndex, i in enumerate(listIn):
	# Catch and replace certain characters that break the string
#	listIn[listIndex][1] = listIn[listIndex][1].replace("\"", " in")
#	listIn[listIndex][1] = listIn[listIndex][1].replace("\'", " ft")
#	listIn[listIndex][1] = listIn[listIndex][1].replace("ø", " Diam")
	
	# Write to columnValues with values wrapped in quptes and separated by commas
#	columnValues += '"' + listIn[listIndex][1] + '"' + ', '
#columnValues = columnValues[:-2]

#for listIndex, i in enumerate(listIn):
#	questionMarks += '?, '
#questionMarks = questionMarks[:-2]

# Create a table in the db
#sqlCommand += "CREATE TABLE " + tableName + " (" + columnNames + ") \n"


#sqlCommand += "VALUES (" + questionMarks + "), " + columnValues
#sqlCommand += "VALUES (" + columnValues + ")"</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Watch guid="48b45785-24c4-44ab-bb5c-63ee2a69837b" type="CoreNodeModels.Watch" nickname="Watch" x="8432.4681604599" y="-2521.07830437305" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.Watch>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="9c59348f-52a4-4aa8-b4b9-f0982e5e0952" start_index="0" end="265aa3c4-9cb6-4d58-a91d-b26d249f6b7f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9c59348f-52a4-4aa8-b4b9-f0982e5e0952" start_index="0" end="7e50d76b-d3f2-435c-9da9-10548b09c3fc" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="b9f62f22-08e3-44b7-84ef-8bc685a0440e" start_index="0" end="648f4ee1-e579-4549-b499-d6d4d87bbb23" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="265aa3c4-9cb6-4d58-a91d-b26d249f6b7f" start_index="0" end="b9f62f22-08e3-44b7-84ef-8bc685a0440e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="265aa3c4-9cb6-4d58-a91d-b26d249f6b7f" start_index="0" end="0fad4b1f-1caf-4a6b-9f7c-0f16a734bad1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7e50d76b-d3f2-435c-9da9-10548b09c3fc" start_index="0" end="af567617-315f-4b53-9a60-a885277cf9bd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0fad4b1f-1caf-4a6b-9f7c-0f16a734bad1" start_index="0" end="8bbcacae-e796-47e4-a8c2-f0cbed06c0fa" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8bbcacae-e796-47e4-a8c2-f0cbed06c0fa" start_index="0" end="648f4ee1-e579-4549-b499-d6d4d87bbb23" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="648f4ee1-e579-4549-b499-d6d4d87bbb23" start_index="0" end="c1ad97c8-2296-4783-8cee-521c3cf28e42" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="648f4ee1-e579-4549-b499-d6d4d87bbb23" start_index="0" end="66055e37-dad2-4e2f-b64e-ebff6f04a1d9" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="66055e37-dad2-4e2f-b64e-ebff6f04a1d9" start_index="0" end="422cd9d4-6381-4a08-9c76-d502a7edc69f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="422cd9d4-6381-4a08-9c76-d502a7edc69f" start_index="0" end="d609f85f-49d5-49d7-867a-ff1478aa59e0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="af567617-315f-4b53-9a60-a885277cf9bd" start_index="0" end="08eb58bc-dfb2-4972-8222-1091d91e4407" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="242199ae-0818-4234-9394-7a5ee23996d9" start_index="0" end="ee128686-19e6-441d-b638-9be057452344" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="af4978d8-1304-4dd3-a278-765ce11e1ee2" start_index="0" end="ee128686-19e6-441d-b638-9be057452344" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d609f85f-49d5-49d7-867a-ff1478aa59e0" start_index="0" end="df46c5f3-6467-4ecb-9c65-c431942b3e7e" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="df46c5f3-6467-4ecb-9c65-c431942b3e7e" start_index="0" end="08eb58bc-dfb2-4972-8222-1091d91e4407" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="08eb58bc-dfb2-4972-8222-1091d91e4407" start_index="0" end="48b45785-24c4-44ab-bb5c-63ee2a69837b" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="48b45785-24c4-44ab-bb5c-63ee2a69837b" start_index="0" end="ee128686-19e6-441d-b638-9be057452344" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="8ac9e161-cadb-4883-b05e-7a88d3fdf013" annotationText="Get all elements and their parameters" left="6197.82275262702" top="-1542.67852085955" width="504.864947919999" height="143.09978976648" fontSize="30" InitialTop="-1496.67852085955" InitialHeight="484.790074722147" TextblockHeight="36" backgrouund="#FF48B9FF">
      <Models ModelGuid="b9f62f22-08e3-44b7-84ef-8bc685a0440e" />
      <Models ModelGuid="265aa3c4-9cb6-4d58-a91d-b26d249f6b7f" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="1f662bcd-726d-44cf-ba97-fb7d55cf9fc7" annotationText="Set Category" left="5686.65358776026" top="-1566.18658248271" width="186" height="139" fontSize="30" InitialTop="-1520.18658248271" InitialHeight="123" TextblockHeight="36" backgrouund="#FFFFB8D8">
      <Models ModelGuid="9c59348f-52a4-4aa8-b4b9-f0982e5e0952" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="0afcb002-947b-4952-b80f-bc2a43927f33" annotationText="Insert Element Id's to beginning of lists" left="6206.71536502778" top="-2216.90195509201" width="919.06399040207" height="565.26147776271" fontSize="30" InitialTop="-2170.90195509201" InitialHeight="410.794833829366" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="0fad4b1f-1caf-4a6b-9f7c-0f16a734bad1" />
      <Models ModelGuid="8bbcacae-e796-47e4-a8c2-f0cbed06c0fa" />
      <Models ModelGuid="648f4ee1-e579-4549-b499-d6d4d87bbb23" />
      <Models ModelGuid="c1ad97c8-2296-4783-8cee-521c3cf28e42" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="90553086-ed7b-435a-a4b0-237d37527423" annotationText="Create list of Element Ids with sublists of parameters" left="7180.09689786937" top="-2298.53793383747" width="488.12152968991" height="461.28624338752" fontSize="30" InitialTop="-2216.53793383747" InitialHeight="408" TextblockHeight="72" backgrouund="#FFC1D676">
      <Models ModelGuid="66055e37-dad2-4e2f-b64e-ebff6f04a1d9" />
      <Models ModelGuid="422cd9d4-6381-4a08-9c76-d502a7edc69f" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="33fb2705-ef00-400e-8b71-8866985488fe" annotationText="Create dictionary of parameters (all elements)" left="7688.01240097086" top="-2303.03986978108" width="465.42622641881" height="472.01116041549" fontSize="30" InitialTop="-2221.03986978108" InitialHeight="124.16000571192" TextblockHeight="72" backgrouund="#FFC1D676">
      <Models ModelGuid="d609f85f-49d5-49d7-867a-ff1478aa59e0" />
      <Models ModelGuid="df46c5f3-6467-4ecb-9c65-c431942b3e7e" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="cdeef2ed-b036-40c0-be28-c7c8d7c8a533" annotationText="Create SQL command" left="8205.32415970128" top="-2567.07830437305" width="527.144000758621" height="424" fontSize="30" InitialTop="-2521.07830437305" InitialHeight="165.58516177868" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="08eb58bc-dfb2-4972-8222-1091d91e4407" />
      <Models ModelGuid="48b45785-24c4-44ab-bb5c-63ee2a69837b" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="0.0669290795922279" eyeY="5.85158491134644" eyeZ="52.2064781188965" lookX="-5.06692886352539" lookY="5.14841508865356" lookZ="-60.2064781188965" upX="0.0248687863349915" upY="0.955019950866699" upZ="0.295496940612793" />
  </Cameras>
</Workspace>